# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Translation Helper'
description: 'A GitHub Action keep your issue or PR in line with international standards.'
author: 'xrkffgg'

branding:
  # https://feathericons.com/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'thumbs-up'
  color: 'red'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  translate-title:
    description: If translate title. Default true.
  translate-body:
    description: If translate body. Default true.

runs:
  using: 'node12'
  main: 'dist/index.js'
